version: "2"
services:
  web:
    build: docker/nginx
    ports:
      - "8088:80"
    links:
      - php
    volumes_from:
      - container:scrumpoker-sync:rw

  php:
    build: docker/php-fpm
    volumes_from:
      - container:scrumpoker-sync:rw
    working_dir: /app
    links:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo
    ports:
    - "27017:27017"

  rabbitmq:
    build: docker/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  scrumpoker-sync:
    external: true