app_game:
    type:     rest
    resource: AppBundle\Controller\GamesController
    defaults: { _format: json }

app_task:
    type:     rest
    resource: AppBundle\Controller\TasksController
    defaults: { _format: json }

app_player:
    type:     rest
    resource: AppBundle\Controller\PlayersController
    defaults: { _format: json }
