services:
    app.util.singularize_inflector:
        class: AppBundle\Util\SingularizeInflector
    app.util_consumer.task_consumer:
        class: AppBundle\Util\Consumer\TaskConsumer
    app.util_manager.game_manager:
        class: AppBundle\Util\Manager\GameManager
        arguments:
            - '@old_sound_rabbit_mq.game_producer'
            - '@app.repositories.game_repository'
            - '@serializer'

    app.util_client.channel_factory:
        class: AppBundle\Util\Client\ChannelFactory

    app.util_listener.game_created_subscriber:
        class: AppBundle\Util\Listener\GameCreatedSubscriber
        arguments:
          - '@pgs_rabbit_mq.service.rabbit_mqpublisher'
          - '@serializer'
        tags:
            - { name: kernel.event_subscriber }

    app.util_listener.task_created_subscriber:
        class: AppBundle\Util\Listener\TaskCreatedSubscriber
        arguments:
          - '@pgs_rabbit_mq.service.rabbit_mqpublisher'
          - '@jms_serializer.serializer'
        tags:
            - { name: kernel.event_subscriber }
