services:
    app.util.singularize_inflector:
        class: AppBundle\Util\SingularizeInflector
    app.util_consumer.task_consumer:
        class: AppBundle\Util\Consumer\TaskConsumer
    app.util_manager.game_manager:
        class: AppBundle\Util\Manager\GameManager
        arguments:
            - '@old_sound_rabbit_mq.game_producer'
            - '@app.repositories.game_repository'
            - '@serializer'
#    app.util_listener.task_subscriber:
#        class: AppBundle\Util\Listener\TaskSubscriber
#        arguments:
#            - '@old_sound_rabbit_mq.task_producer'

    app.util_client.rabbit_client:
        class: AppBundle\Util\Client\RabbitClient
        arguments:
            - '%rabbitmq.host%'
            - '%rabbitmq.vhost%'
            - '%rabbitmq.user%'
            - '%rabbitmq.password%'

    app.util_client.channel.task:
        class: AppBundle\Util\Client\ChannelFactory
        factory:   ['@app.util_client.channel_factory', create]
        arguments:
            - '@app.util_client.rabbit_client'
            - 'task'

    app.util_client.channel_factory:
        class: AppBundle\Util\Client\ChannelFactory
