services:
    app.util.singularize_inflector:
        class: AppBundle\Util\SingularizeInflector

    app.util_client.channel_factory:
        class: AppBundle\Util\Client\ChannelFactory

    app.util_listener.game_created_subscriber:
        class: AppBundle\Util\Listener\GameCreatedSubscriber
        arguments:
          - '@pgs_rabbit_mq.service.rabbit_mqpublisher'
          - '@serializer'
        tags:
            - { name: kernel.event_subscriber }

    app.util_listener.game_started_subscriber:
        class: AppBundle\Util\Listener\GameStartedSubscriber
        arguments:
          - '@pgs_rabbit_mq.service.rabbit_mqpublisher'
          - '@serializer'
        tags:
            - { name: kernel.event_subscriber }

    app.util_listener.task_subscriber:
        class: AppBundle\Util\Listener\TaskSubscriber
        arguments:
          - '@pgs_rabbit_mq.service.rabbit_mqpublisher'
          - '@jms_serializer.serializer'
        tags:
            - { name: kernel.event_subscriber }

    app.util_listener.player_subscriber:
        class: AppBundle\Util\Listener\PlayerSubscriber
        arguments:
          - '@jms_serializer.serializer'
          - '@pgs_rabbit_mq.service.rabbit_mqpublisher'
          - '@app.repositories.player_repository'
        tags:
            - { name: kernel.event_subscriber }
    app.util_service.dropout_message_consumer:
        class: AppBundle\Util\Service\DropoutMessageConsumerService
        arguments:
          - '@app.repositories.game_repository'
          - '@app.repositories.player_repository'
          - '@fos_rest.serializer'
          - '@event_dispatcher'

    dropout_consumer:
        alias: 'app.util_service.dropout_message_consumer'

    app.util_service.results:
        class: AppBundle\Util\Service\ResultsService