AppBundle\Document\Player:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: string
        name:
            expose: true
            type: string
        guid:
            expose: true
            type: string
        email:
            expose: true
            type: string
