AppBundle\Document\Task:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: string
        name:
            expose: true
            type: string
        status:
            expose: true
            type: string
        votes:
            expose: true
            type: array<AppBundle\Document\Vote>