AppBundle\Document\Game:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: string
        name:
            expose: true
            type: string
        status:
            expose: true
            type: string
        currentTaskId:
            expose: true
            type: string
        tasks:
            expose: true
            type: array<AppBundle\Document\Task>
        players:
            expose: true
            type: array<AppBundle\Document\Player>