AppBundle\Document\Game:
    repositoryClass: AppBundle\Repositories\GameRepository
    collection: game
    fields:
        id:
            id:  true
        name:
            type: string
    embedMany:
        userStories:
            targetDocument: UserStory
