AppBundle\Document\Game:
    repositoryClass: AppBundle\Repositories\GameRepository
    collection: game
    fields:
        id:
            id:  true
        name:
            type: string
        players:
            type: collection
        status:
            type: string
    embedMany:
        tasks:
            targetDocument: Task
    embedOne:
        currentTask:
            targetDocument: Task
