AppBundle\Document\Game:
    repositoryClass: AppBundle\Repositories\GameRepository
    collection: game
    fields:
        id:
            id:  true
        name:
            type: string
        status:
            type: string
        currentTaskId:
            type: string
    embedMany:
        tasks:
            targetDocument: AppBundle\Document\Task
    referenceMany:
        players:
            targetDocument: AppBundle\Document\Player
            cascade: all