AppBundle\Document\Vote:
    type: embeddedDocument
    fields:
        id:
            id:  true
        value:
            type: integer
    referenceOne:
        player:
            targetDocument: AppBundle\Document\Player
            cascade: all