AppBundle\Model\Vote:
    type: embeddedDocument
    fields:
        id:
            id:  true
        player:
            type: string
        value:
            type: integer
    embedOne:
        task:
            type: Task
